services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: go-template
      POSTGRES_PASSWORD: go-template
      POSTGRES_DB: go-template
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pg_data:
  rabbitmq_data: