services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: go-template
      POSTGRES_PASSWORD: go-template
      POSTGRES_DB: go-template
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_data: