#!/bin/bash
# Check if golangci-lint is installed
if ! command -v golangci-lint &> /dev/null; then
    echo "golangci-lint could not be found, installing..."
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
fi

# Run golangci-lint and capture the output
if [ -n "$GO_FILES" ]; then
    echo "Running golangci-lint..."
    $(go env GOPATH)/bin/golangci-lint -c ./tools/.golangci.yml run --fix

   echo "Go code formatting applied successfully."
fi
